### PR TITLE
Added linux export + UX simplification

### PR DESCRIPTION
**Pull request by JamesPerisher**
Added Linux export preset
Added new companion preset
Modified age selector for companion creation to allow setting of custom age

### CODE REVIEW

**Review by CDcruzCode — APPROVED** [review]
I haven't been able to test the Linux export (I don't run linux) but I assume it works.

**Comment by CDcruzCode** [comment]
I'm going to be honest, I haven't used Github that much except for posting my own code. I don't really understand how pull requests work. Thank you for your pull request though.

I approve the Linux export & age select changes.
The companion preset should be a personality type rather than a name. It may be better suited as a general chatting prompt as I still need to work out a lot of things for how the companion mode works.

**Comment by JamesPerisher** [comment]
No problem, I'll amend the pr so u can approve? Also how do you feel about the age being a selectable via an input instead of randomised ranges?

**Comment by CDcruzCode** [comment]
Sorry! I just broke your pr. I was trying to work out how to push my code (I've just been using the webUI before).
Yes I agree age can be selectable.
My reasoning for the age ranges was to have additional system prompts to tell the AI how to act for certain age ranges, but that can be done even with a selectable age.

**Comment by CDcruzCode** [comment]
Sorry! I just broke your pr. I was trying to work out how to push my code
(I've just been using the webUI before).
Yes I agree age can be selectable.
My reasoning for the age ranges was to have additional system prompts to
tell the AI how to act for certain age ranges, but that can be done even
with a selectable age.

**Pull request closed without merging**
